apiVersion: ://coreos.com
kind: ServiceMonitor
metadata:
  name: portfolio-backend-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: [portfolio-backend, increment-visitor-counter]
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
