apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: portfolio-frontend-config
  namespace: default
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT # Enforces an instant 301 redirect
