apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "portfolio-static-ip"
    networking.gke.io/frontend-config: "portfolio-frontend-config"
    networking.gke.io/managed-certificates: "portfolio-managed-cert-v2"
spec:
  ingressClassName: gce
  rules:
  - host: pcurtcast.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: portfolio-backend-service
            port:
              number: 80
      - path: /api/counter
        pathType: Prefix
        backend:
          service:
            name: increment-visitor-counter-service
            port:
              number: 80
      - path: /dashboard
        pathType: Prefix
        backend:
          service:
            name: grafana-service  # Your internal K8s service name
            port:
              number: 80           # The port your service exposes

  - host: www.pcurtcast.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: portfolio-backend-service
            port:
              number: 80
      - path: /api/counter
        pathType: Prefix
        backend:
          service:
            name: increment-visitor-counter-service
            port:
              number: 80
      - path: /dashboard
        pathType: Prefix
        backend:
          service:
            name: grafana-service  # Your internal K8s service name
            port:
              number: 80           # The port your service exposes
